# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 18fd6873f73391190724b1f7ee8f9fa4c1d81e0ba1403e76ed038d0218725a899e9fb30f06694f687c7df4dfa3b7f9cd6bb883a60919ae740fda297e38d675d3

test:
  secret_key_base: 326d8628573d652c9a9985cd1db4f2853e6bb684d24099dfb77cc94c1855d877b5088eb9e17085c9fb1edd25ac4bd43d928958c0c34aaced83eeaacdc0794aad

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
